000.index=OceanBase 云平台文档
100.product-introduction=产品简介
500.restrictions=使用限制
200.deployment-guide=部署指南
300.installation-planning=安装规则
500.prepare-metadb-and-monitordb=准备 MetaDB 和 MonitorDB
800.deploy-appendix=附录
300.ob-cloud-platform=用户指南
300.userguide-features=功能介绍
100.cluster-features=集群功能
200.tenant-functions=租户功能
300.host-features=主机功能
500.obproxy=OBProxy 功能
700.system-management-features=系统管理功能
800.user-center=个人中心
400.password-box=密码箱
400.manage-clusters=管理集群
300.basic-operations=集群基础操作
700.manage-cluster-zones=管理集群 Zone
800.manage-the-observer-cluster=管理集群 OBServer
1100.merge-management=合并管理
1200.parameters=参数管理
500.manage-tenants=管理租户
200.basic-tenant-operations=租户基础操作
1000.sql-diagnostics=SQL 诊断
1100.session-management=会话管理
1200.userguide-parameters=参数管理
600.management-host=管理主机
700.manage-software-packages=管理软件包
800.obproxy-management=管理 OBProxy
900.use-alert-management=使用告警管理
1000.using-system-management=使用系统管理
1200.appendix=附录
400.alarm-reference=告警参考
200.ob-alert=OB 告警
300.application-alert=应用告警
400.alarm-appendix=附录
500.api-reference=API 参考
300.cluster-information=集群信息
400.tenant-information=租户信息
1800.ob-database-management=OB 数据库管理
500.host-module=主机模块
600.software-package-interface=软件包接口
700.api-obproxy-management=OBProxy 管理
800.monitoring=监控
900.alert=告警
100.alert-events=告警事件
200.alert-notification=告警通知
1000.task-management-interface=任务管理接口
1100.ob-user-and-permission-management=OB 用户与权限管理
1200.ocp-agent-management=OCP Agent 管理
1300.sql-performance=SQL 性能
1400.other=其它
1500.api-appendix=附录
