100.product-introduction=Product Introduction
400.restrictions=Limits
200.deployment-guide=Deployment Guide
300.installation-planning=Installation planning
500.prepare-metadb-and-monitordb=Prepare MetaDB and MonitorDB
800.deploy-appendix=Appendix
300.ob-cloud-platform=User Guide
300.userguide-features=Features
100.cluster-features=Clusters
200.tenant-functions=Tenants
300.host-features=Hosts
500.obproxy=OBProxy
700.system-management-features=System management
800.user-center=Personal center
400.password-box=Password box
400.manage-clusters=Manage clusters
300.basic-operations=Basic cluster operations
700.manage-cluster-zones=Manage zones of a cluster
800.manage-the-observer-cluster=Manage OBServers of a cluster
1100.merge-management=Major compaction management
1200.parameters=Manage parameters
500.manage-tenants=Manage tenants
200.basic-tenant-operations=Basic tenant operations
1000.sql-diagnostics=SQL diagnostics
1100.session-management=Manage sessions
1200.userguide-parameters=Manage parameters
600.management-host=Manage hosts
700.manage-software-packages=Manage software packages
800.obproxy-management=Manage OBProxies
900.use-alert-management=Manage alerts
1000.using-system-management=Use system management
1200.appendix=Appendix
400.alarm-reference=Alert Reference
200.ob-alert=OceanBase alerts
300.application-alert=Application alerts
400.alarm-appendix=Appendix
500.api-reference=API Reference
300.cluster-information=Cluster information
400.tenant-information=Tenant information
1800.ob-database-management=OceanBase database management
500.host-module=Hosts
600.software-package-interface=Software packages
700.api-obproxy-management=OBProxy management
800.monitoring=Monitoring
900.alert=Alerts
100.alert-events=Alert events
200.alert-notification=Alert notifications
1000.task-management-interface=Task management
1100.ob-user-and-permission-management=OceanBase user and privilege management
1200.ocp-agent-management=OCP Agent management
1300.sql-performance=SQL performance
1400.other=Others
1500.api-appendix=Appendix
