1.product-introduction=Product Introduction
4.restrictions=Limits
2.deployment-guide=Deployment Guide
3.installation-planning=Installation planning
5.prepare-metadb-and-monitordb=Prepare MetaDB and MonitorDB
8.deploy-appendix=Appendix
3.ob-cloud-platform=User Guide
3.userguide-features=Features
1.cluster-features=Clusters
2.tenant-functions=Tenants
3.host-features=Hosts
5.obproxy=OBProxy
7.system-management-features=System management
8.user-center=Personal center
4.password-box=Password box
4.manage-clusters=Manage clusters
3.basic-operations=Basic cluster operations
7.manage-cluster-zones=Manage zones of a cluster
8.manage-the-observer-cluster=Manage OBServers of a cluster
11.merge-management=Major compaction management
12.parameters=Manage parameters
5.manage-tenants=Manage tenants
2.basic-tenant-operations=Basic tenant operations
10.sql-diagnostics=SQL diagnostics
11.session-management=Manage sessions
12.userguide-parameters=Manage parameters
6.management-host=Manage hosts
7.manage-software-packages=Manage software packages
8.obproxy-management=Manage OBProxies
9.use-alert-management=Manage alerts
10.using-system-management=Use system management
12.appendix=Appendix
4.alarm-reference=Alert Reference
2.ob-alert=OceanBase alerts
3.application-alert=Application alerts
4.alarm-appendix=Appendix
5.api-reference=API Reference
3.cluster-information=Cluster information
4.tenant-information=Tenant information
18.ob-database-management=OceanBase database management
5.host-module=Hosts
6.software-package-interface=Software packages
7.api-obproxy-management=OBProxy management
8.monitoring=Monitoring
9.alert=Alerts
1.alert-events=Alert events
2.alert-notification=Alert notifications
10.task-management-interface=Task management
11.ob-user-and-permission-management=OceanBase user and privilege management
12.ocp-agent-management=OCP Agent management
13.sql-performance=SQL performance
14.other=Others
15.api-appendix=Appendix