200.product-introduction=Product Introduction
400.restrictions=Limits
300.deployment-guide=Deployment OceanBase Cloud Platform (OCP)
100.deploying-enterprise-ocp=Deploy OceanBase Cloud Platform (OCP) Enterprise Edition
100.deployment-overview=Deployment overview
200.prepare-the-deployment-environment=Prepare the deployment environment
300.deployment=Deploy OCP
100.planning-resources=Plan resources
100.planning-resources-of-single-node=Planning resources of a single node OCP
200.planning-resources-of-high-availability=Planning resources of a high availability OCP
200.deploying-ocp=Deploy OCP
100.deploying-a-single-point-of-ocp=Deploying a single point of OCP
200.deploying-a-high-availability-of-ocp=Deploying a high availability of OCP
400.deployment-faq=Deployment FAQ
200.f5-ltm-and-alert-configuration=F5 Big-IP LTM and alert configuration
200.deploying-community-ocp=Deploy OceanBase Cloud Platform (OCP) Community Edition
300.installation-planning=Installation planning
700.deploy-appendix=Appendix
400.upgrade-guide=Upgrade OceanBase Cloud Platform (OCP)
100.upgrade-enterprise-ocp=Upgrade OceanBase Cloud Platform (OCP) Enterprise Edition
400.upgrade-ocp-guide=Upgrade OCP
500.verify-after-upgrade=Verify after upgrade
600.upgrade-appendix=Appendix
200.upgrade-community-ocp=Upgrade OceanBase Cloud Platform (OCP) Community Edition
500.quickstart=Quick Start
600.cluster-functions=Clusters Management
200.create-a-cluster=Create a cluster
300.manage-a-cluster=Manage clusters
400.manage-arbitration-services=Manage Arbitration Service
500.manage-a-zone=Manage zones of a cluster
600.manage-an-observer=Manage OBServers of a cluster
1000.manage-cluster-resource=Manage cluster resource
1100.manage-cluster-merge=Manage major compaction of a cluster
1300.manage-cluster-parameters=Manage cluster parameters
700.tenant-functions=Tenants Management
600.manage-a-tenant=Manage tenants
900.manage-tenant-topulogy=Manage topulogy of a tenant
1000.manage-tenant-replica=Manage replicas of a tenant
1200.manage-users-and-permissions-under-tenants=Manage users and permissions under a tenant
200.user-management-under-an-oracle-tenant=Manage user under an Oracle tenant
1250.manage-resource-isolation=Manage resource isolation
1400.manage-tenant-merge=Manage major compaction under a tenant
1600.manage-tenant-parameters=Manage tenant parameters
800.obproxy-functions=OBProxies management
300.manage-a-obproxy-cluster=Manage OBProxy Clusters
400.manage-a-obproxy-server=Manage OBProxy Servers
900.monitoring-and-alerts-functions=Monitoring and Alerts management
100.performance-monitoring-overview=Manage monitoring
200.alert-management=Use the alert feature
300.manage-alert-rules=Manage alert rules
400.manage-alert-templates=Manage alert templates
500.manage-alert-channels=Manage alert channels
600.manage-alert-push=Manage alert push
800.manage-blocking-conditions=Manage blocking conditions
300.use-the-inspection-feature=Use the inspection feature
200.configure-the-rules=Configure Scheduling Rules
400.initate-a-inspection=Initiate Inspection
600.manage-inspection-report=Manage Inspection reports
1000.diagnosis-and-tuning-fuctions=Diagnosis and tuning fuctions
100.manage-sql-diagnosis=SQL Diagnostics
100.sql-diagnostics-introduction=SQL Diagnostics Introduction
200.manage-transaction-diagnostics=Transaction Diagnostics
300.manage-session=Manage sessions
600.manage-the-reports=View diagnostics reports
1100.backup-and-restoration-functions=Use backup and recovery
400.backup-now=Backup now
500.regular-backup=Regular backup
100.manage-cluster-backup-strategy=Manage cluster-level backup strategy
200.manage-tenant-backup-strategy=Manage tenant-level backup strategy
600.manage-backup-tasks=Manage backup tasks
800.regular-recovery=Regular recovery
1000.manage-backup-and-recovery-service=Manage backup and recovery service
1200.manage-disaster-recovery=Disaster recovery management
100.switching-primary-and-standby-tenants=Switching primary and standby tenants
200.switching-primary-and-standby-databases=Switching primary and standby databases
300.ocp-multi-cluster-mode=OCP Manage OCP clusters in the multi-cluster mode
400.ocp-multi-zone-mode=OCP Manage OCP in multi-zone mode
1300.log-service=Log service
850.host-features=Hosts management
1500.manage-software-packages=Software packages management
1600.system-management-features=System management
300.manage-system-parameter=Manage system parameters
400.manage-roles=Manage roles
500.manage-users=Manage users
600.management-user-center=User center management
300.manage-password-box=Manage password box
300.common-o-m-problems=FAQ on O&M
400.common-monitoring-problems=FAQ on monitoring
1800.sql-tuning-practices=SQL Tuning Practices
100.how-to-locate-abnormal-sql=Locate General Abnormal SQL Statements
200.custom-exception-sql-rules=Customize Abnormal SQL Statement Determining Rules
300.common-sql-performance-tuning=General SQL Performance Tuning Scenarios
100.execution-plan-optimization=Execution Plan Optimization
200.index-optimization=Index Optimization
1900.reference-guide=Reference guide
100.alarm-reference=Alarm reference
200.ob-alert=OceanBase alerts
300.application-alert=Application alerts
400.oas-alert=OAS alerts
500.appendix=Appendix
200.api-reference=API Reference
450.cluster-information=Cluster information
500.tenant-information=Tenant information
1900.ob-database-management=OceanBase database management
600.host-module=Hosts
700.software-package=Software packages
800.obproxy-management=OBProxy management
900.monitoring=Monitoring
1000.alert=Alerts
200.alert-events=Alert events
300.alert-notification=Alert notifications
1100.task-management=Task management
1200.ocp-historical-events=OCP event history
1300.ob-user-and-permission-management=OceanBase user and privilege management
1400.ocpagent-management=OCP Agent management
1500.sql-performance=SQL performance
1600.backup-and-restoration-3=Backup and recovery
1700.health-examination=Health examination
300.monitoring-indicator-reference=Metric reference
300.ob-cluster=OceanBase cluster
400.oceanbase-database-tenant=OceanBase Database tenant
500.obproxy-cluster=OBProxy cluster
600.host=Host
2000.faq=FAQ
2100.appendix=Appendix