1.product-introduction=产品简介
5.restrictions=使用限制
2.deployment-guide=部署指南
3.installation-planning=安装规则
9.deploy-appendix=附录
3.ob-cloud-platform=用户指南
3.userguide-features=功能介绍
1.cluster-features=集群功能
2.tenant-functions=租户功能
3.host-features=主机功能
5.obproxy=OBProxy 功能
7.system-management-features=系统管理功能
8.user-center=个人中心
4.password-box=密码箱
4.manage-clusters=管理集群
3.basic-operations=集群基础操作
7.manage-cluster-zones=管理集群 Zone
8.manage-the-observer-cluster=管理集群 OBServer
11.backup-clusters=集群备份恢复
12.merge-management=合并管理
13.parameters=参数管理
5.manage-tenants=管理租户
2.basic-tenant-operations=租户基础操作
10.sql-diagnostics=SQL 诊断
11.session-management=会话管理
12.userguide-parameters=参数管理
6.management-host=管理主机
7.manage-software-packages=管理软件包
8.obproxy-management=管理 OBProxy
9.use-alert-management=使用告警管理
10.using-system-management=使用系统管理
12.appendix=附录
4.alarm-reference=告警参考
2.ob-alert=OB 告警
3.application-alert=应用告警
4.alarm-appendix=附录
5.api-reference=API 参考
3.cluster-information=集群信息
4.tenant-information=租户信息
18.ob-database-management=数据库管理
5.host-module=主机模块
6.software-package-interface=软件包接口
7.api-obproxy-management=OBProxy 管理
8.monitoring=监控
9.alert=告警
1.alert-events=告警事件
2.alert-notification=告警通知
10.task-management-interface=任务管理接口
11.ob-user-and-permission-management=OB 用户与权限管理
12.ocp-agent-management=OCP Agent 管理
13.sql-performance=SQL 性能
14.other=其它
15.api-appendix=附录
0.index=OceanBase 云平台文档